# Kubernetes Manifest file to create a Hyperledger Validating Peer Services
# Date : 22-08-2016
# Version 0.1
# Author : James Buckett (james.buckett@au1.ibm.com)
# Commissioned by ANZ Bank under direction of Ben Smillie (Ben.Smillie@anz.com)

apiVersion: v1        
kind: Service

metadata:
  # Hyperledger Validating Peer Service Definition 
  name: svc-hl-vp0
  namespace: hyperledger
  labels:
    app: hl-vp0
    tier: validating-peer
spec:
  type: LoadBalancer

  ports:
    # 30303: Peer service listening port
  - name: peer-service
    port: 30303
    targetPort: 30303

    # 30304: CLI process use it for callbacks from chain code
  - name: cli-callback 
    port: 30304
    targetPort: 30304

    # 31315: Event service on validating node
  - name: event-service 
    port: 31315
    targetPort: 31315
    protocol: TCP

    # 5000: REST service listening port
  - name: rest-service 
    port: 5000
    targetPort: 5000
    protocol: TCP

  # Like the selector in the replication controller,
  # but this time it identifies the set of Hyperledger 
  # pods to load balance traffic to.
  selector:
    app: hl-vp0
--- 
apiVersion: v1
kind: Service

metadata:
  # Hyperledger Validating Peer Service Definition 
  name: svc-hl-vp1
  namespace: hyperledger
  labels:
    app: hl-vp1
    tier: validating-peer
spec:
  type: LoadBalancer

  ports:
    # 30303: Peer service listening port
  - name: peer-service
    port: 30303
    targetPort: 30303

    # 30304: CLI process use it for callbacks from chain code
  - name: cli-callback 
    port: 30304
    targetPort: 30304

    # 31315: Event service on validating node
  - name: event-service 
    port: 31315
    targetPort: 31315
    protocol: TCP

    # 5000: REST service listening port
  - name: rest-service 
    port: 5000
    targetPort: 5000
    protocol: TCP

  # Like the selector in the replication controller,
  # but this time it identifies the set of Hyperledger 
  # pods to load balance traffic to.
  selector:
    app: hl-vp1
--- 
apiVersion: v1
kind: Service

metadata:
  # Hyperledger Validating Peer Service Definition 
  name: svc-hl-vp2
  namespace: hyperledger
  labels:
    app: hl-vp2
    tier: validating-peer
spec:
  type: LoadBalancer

  ports:
    # 30303: Peer service listening port
  - name: peer-service
    port: 30303
    targetPort: 30303

    # 30304: CLI process use it for callbacks from chain code
  - name: cli-callback 
    port: 30304
    targetPort: 30304

    # 31315: Event service on validating node
  - name: event-service 
    port: 31315
    targetPort: 31315
    protocol: TCP

    # 5000: REST service listening port
  - name: rest-service 
    port: 5000
    targetPort: 5000
    protocol: TCP

  # Like the selector in the replication controller,
  # but this time it identifies the set of Hyperledger 
  # pods to load balance traffic to.
  selector:
    app: hl-vp2
--- 
apiVersion: v1
kind: Service

metadata:
  # Hyperledger Validating Peer Service Definition 
  name: svc-hl-vp3
  namespace: hyperledger
  labels:
    app: hl-vp3
    tier: validating-peer
spec:
  type: LoadBalancer

  ports:
    # 30303: Peer service listening port
  - name: peer-service
    port: 30303
    targetPort: 30303

    # 30304: CLI process use it for callbacks from chain code
  - name: cli-callback 
    port: 30304
    targetPort: 30304

    # 31315: Event service on validating node
  - name: event-service 
    port: 31315
    targetPort: 31315
    protocol: TCP

    # 5000: REST service listening port
  - name: rest-service 
    port: 5000
    targetPort: 5000
    protocol: TCP

  # Like the selector in the replication controller,
  # but this time it identifies the set of Hyperledger 
  # pods to load balance traffic to.
  selector:
    app: hl-vp3